"""human_email colum nullable

Revision ID: 2313b58bb54d
Revises: 7cbd55b0878d
Create Date: 2022-08-08 11:35:54.482538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2313b58bb54d'
down_revision = '7cbd55b0878d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('human_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human', 'human_email')
    # ### end Alembic commands ###
