"""type of pet column added

Revision ID: 43bf4646f90d
Revises: 89111787469f
Create Date: 2022-08-01 21:50:10.046126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bf4646f90d'
down_revision = '89111787469f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'type')
    # ### end Alembic commands ###
