"""age and size added to pet table

Revision ID: 7cbd55b0878d
Revises: d4a9f794eaa8
Create Date: 2022-08-06 23:36:54.933116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbd55b0878d'
down_revision = 'd4a9f794eaa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('age', sa.String(), nullable=True))
    op.add_column('pet', sa.Column('size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'size')
    op.drop_column('pet', 'age')
    # ### end Alembic commands ###
