"""human, pet, post models created

Revision ID: 89111787469f
Revises: 
Create Date: 2022-08-01 01:41:50.903569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89111787469f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human',
    sa.Column('human_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('human_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('human_id')
    )
    op.create_table('pet',
    sa.Column('pet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_name', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['human_id'], ['human.human_id'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('is_claim', sa.Boolean(), nullable=False),
    sa.Column('reference_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['human.human_id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.pet_id'], ),
    sa.ForeignKeyConstraint(['reference_post_id'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('pet')
    op.drop_table('human')
    # ### end Alembic commands ###
