"""Created post status and description columns

Revision ID: d4a9f794eaa8
Revises: 43bf4646f90d
Create Date: 2022-08-03 16:30:48.388283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a9f794eaa8'
down_revision = '43bf4646f90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.String(), nullable=True))
    op.add_column('post', sa.Column('post_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_status')
    op.drop_column('post', 'category')
    # ### end Alembic commands ###
